version: "3"

services:
  app:
    build: .
    volumes:
    - .:/usr/src/app/
    restart: always
    environment:
      PG_DSN: postgresql://postgres:password@postgres/postgres
      DEPLOYMENT_TYPE: PROD
#    depends_on:
#      migration:
#        condition: service_completed_successfully

  migration:
    build: .
    command: python migrate.py
    environment:
      PG_DSN: postgresql://postgres:password@postgres/postgres
    volumes:
      - .:/usr/src/app/
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    restart: always
    build: pgvector/pgvector:pg17
    container_name: pgvector
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
