"""add ivfflat index

Revision ID: 4522c1f582c0
Revises: 7ab3ab2be819
Create Date: 2025-01-31 18:20:23.852532

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4522c1f582c0"
down_revision: Union[str, None] = "7ab3ab2be819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET maintenance_work_mem = "128MB"')
    op.create_index(
        "jokes_embedding_idx",
        "jokes",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "jokes_embedding_idx",
        table_name="jokes",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    # ### end Alembic commands ###
