"""Initial migration

Revision ID: ad12450c8523
Revises: 
Create Date: 2025-02-01 01:27:02.874015

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad12450c8523"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute('SET maintenance_work_mem = "128MB";')
    op.create_table(
        "jokes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("comments_count", sa.Integer(), nullable=False),
        sa.Column("likes_count", sa.Integer(), nullable=False),
        sa.Column("has_my_like", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=2000), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jokes_external_id"), "jokes", ["external_id"], unique=True)
    op.create_index(
        "jokes_embedding_idx",
        "jokes",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "jokes_embedding_idx",
        table_name="jokes",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_l2_ops"},
        if_exists=True,
    )
    op.drop_index(op.f("ix_jokes_external_id"), table_name="jokes", if_exists=True)
    op.drop_table("jokes", if_exists=True)
    # ### end Alembic commands ###
