"""Added chat settings

Revision ID: baad796c3c2b
Revises: ad12450c8523
Create Date: 2025-03-12 16:03:35.365023

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'baad796c3c2b'
down_revision: Union[str, None] = 'ad12450c8523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_settings_chat_id'), 'chat_settings', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_settings_chat_id'), table_name='chat_settings')
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
